platform :ios, '10.0'

target 'OTNetworkTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OTNetworkTest
  pod 'OpenTok', '2.16.0'

end
