/* eslint-disable react-native/no-inline-styles */
import React, {Component} from 'react';
import {View} from 'react-native';
import {OTSession, OTPublisher, OTSubscriber} from '@vonage/client-sdk-video-react-native';

class App extends Component {
  constructor(props) {
    super(props);
    // This is a Vonage application ID (not an API key):
    this.apiKey = 'c696b10d-a8ea-4eae-9cbd-9017c3e05e71';
    this.sessionId =
    '2_MX5jNjk2YjEwZC1hOGVhLTRlYWUtOWNiZC05MDE3YzNlMDVlNzF-fjE3MTE0MTA2OTE4NDh-MThod25Sc0ZTWFZXWXUrTCtub1J3MGVzfn5-';
    // This is a JWT token generated by the Vonage server SDK
    this.token =
    'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6InNlc3Npb24uY29ubmVjdCIsInNlc3Npb25faWQiOiIyX01YNWpOamsyWWpFd1pDMWhPR1ZoTFRSbFlXVXRPV05pWkMwNU1ERTNZek5sTURWbE56Ri1makUzTVRFME1UQTJPVEU0TkRoLU1UaG9kMjVTYzBaVFdGWlhXWFVyVEN0dWIxSjNNR1Z6Zm41LSIsInJvbGUiOiJwdWJsaXNoZXIiLCJpbml0aWFsX2xheW91dF9jbGFzc19saXN0IjoiIiwic3ViIjoidmlkZW8iLCJhY2wiOnsicGF0aHMiOnsiL3Nlc3Npb24vKioiOnt9fX0sImV4cCI6MTcxMTQ5NzA5MiwianRpIjoiOGY3YmY5MzEtY2NhMy00MmZkLWI2NDQtZDRiNzQwZTQ0MDllIiwiaWF0IjoxNzExNDEwNjkxLCJhcHBsaWNhdGlvbl9pZCI6ImM2OTZiMTBkLWE4ZWEtNGVhZS05Y2JkLTkwMTdjM2UwNWU3MSJ9.ItNp_9pvvlgI6pUp1EosFwV5nIMvYJorlGkbrxFVyQ-fng5USA5XTcQ0YbVrdu2pT04DZp0U618BAZuYUyOf70LD4mj9329M0DDi8mbUW43YcKKtDNP-C1dkQVpZIEvrT53pt6lPUOCME_SA6-VT7MZP8-PmoOO6Tq_p1XfFw05yVRMXPk_mSp6eyXoaImfykfFuN2hjYUV3bFzh5PmrfBru_lA7AD6VVAig_qALwBFBSe_j6GRFZVJbDk8WpjX20Uzg3b3qu-4zZJ_fJmkyfebOLpGdBFoQMyfv1kcppizivwUvQTv7bgPLhxTJQAfOrLR2tLANj_emnbjSBJvJbw';
  }

  render() {
    return (
      <View
        style={{
          flex: 1,
          flexDirection: 'column',
          paddingHorizontal: 100,
          paddingVertical: 50,
        }}>
        <OTSession
          apiKey={this.apiKey}
          sessionId={this.sessionId}
          token={this.token}
          eventHandlers={{
            otrnError: console.log,
            error: console.log,
            sessionConnected: console.log,
          }}
          >
          <OTPublisher style={{width: 200, height: 200}} />
          <OTSubscriber style={{width: 200, height: 200}} />
        </OTSession>
      </View>
    );
  }
}

export default App;
